import express from 'express';
import bcrypt from 'bcrypt';
import pool from '../config/db.js';

const router = express.Router();

// Development-only: reset password for an admin or employee by email
router.post('/reset-password', async (req, res, next) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ success: false, message: 'email and password are required' });
    }

    const hash = await bcrypt.hash(String(password), 10);

    // Update admins
    try {
      await pool.query('UPDATE admins SET password_hash = ? WHERE email = ?', [hash, email]);
    } catch (e) {
      // ignore if admins table doesn't exist in this DB
    }

    // Update employees
    try {
      await pool.query('UPDATE employees SET password_hash = ? WHERE email = ?', [hash, email]);
    } catch (e) {
      // ignore
    }

    res.json({ success: true, message: 'Password reset (development only)' });
  } catch (error) {
    next(error);
  }
});

// Development-only: create or update an admin account with a known password
router.post('/create-admin', async (req, res, next) => {
  try {
    const { email, full_name, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ success: false, message: 'email and password are required' });
    }

    const normalized = String(email).trim().toLowerCase();
    const hash = await bcrypt.hash(String(password), 10);

    try {
      // Try update first
      const [updateResult] = await pool.query('UPDATE admins SET password_hash = ?, full_name = ? WHERE email = ?', [hash, full_name || normalized, normalized]);
      // If no rows updated, insert
      if (updateResult && (updateResult.rowCount === 0 || updateResult.affectedRows === 0)) {
        await pool.query('INSERT INTO admins (full_name, email, password_hash, role) VALUES (?, ?, ?, ?)', [full_name || normalized, normalized, hash, 'admin']);
      }
    } catch (e) {
      // If admins table doesn't exist, attempt to create admins table and insert
      try {
        await pool.query(`CREATE TABLE IF NOT EXISTS admins (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          full_name TEXT NOT NULL,
          email TEXT NOT NULL UNIQUE,
          password_hash TEXT NOT NULL,
          role TEXT NOT NULL DEFAULT 'admin',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )`);
        await pool.query('INSERT INTO admins (full_name, email, password_hash, role) VALUES (?, ?, ?, ?)', [full_name || normalized, normalized, hash, 'admin']);
      } catch (err) {
        console.error('Failed to upsert admin in DB', err);
      }
    }

    res.json({ success: true, message: 'Admin created/updated (development only)' });
  } catch (error) {
    next(error);
  }
});

export { router as devRoutes };
